eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true   
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.49.2:31489/eureka 


server:
  port: 8081



spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user_db
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin123



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


  application:
    name: USER-SERVICE  