# Pull a lightweight version of Ubuntu
FROM ubuntu:22.04


# Set environment variables for non-interactive installations
ENV DEBIAN_FRONTEND=noninteractive

# Install Java 17, Maven, Git, and other necessary packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-17-jdk \
    maven -y \
    git -y \
    ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

USER root    

# Set JAVA_HOME environment variable
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH



# Verify installations
RUN echo $PATH

RUN echo $JAVA_HOME && \
    java -version && \
    javac -version && \
    mvn -version && \
    git --version


# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the user service project files into the container
COPY . /usr/src/app

# Build the project using Maven
RUN mvn clean package

# Expose the port that the user service will run on
EXPOSE 8081

# Run the user service
CMD ["java", "-jar", "target/user-service.jar"]