eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://13.127.217.126:8761/eureka
server:
  port: 8081



spring:
  datasource:
    url: jdbc:mysql://user.cto8iauaqiow.ap-south-1.rds.amazonaws.com:3306/userdb
    username: admin

    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin123



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


  application:
    name: USER-SERVICE

#  config:
#    import: configserver:http://localhost:8888/

